### ISSUE TITLE
More testing is required

### ISSUE THREAD

**Issue by metaturso** [brianfreytag/php-bijective#2]
I'd like to thank you for this library.

As far as I could see there's only one unit tests that checks the interface as well as the baseline behaviour of the class.

This test case also contains a single test method which inspects the bijection function for correctness. Since this library is only meant to provide a bijective function, why aren't there more tests to ensure the `encode` and its reverse `decode` function are in fact bijective?

It would be nice to see a test that proves those functions are indeed injective and surjective across some alphabets.

**Comment by brianfreytag** [comment]
I agree, but I don't really have the time at this juncture to produce these tests. If you were interested, I'd be happy to merge some unit tests if you were to push them up.

**Comment by brianfreytag** [comment]
OP did not submit a PR to add tests for nearly a year. Closing task out.
